title: "Mina Kebriaee — AI, Data & Cloud Projects"
description: "A portfolio of data, AI, and cloud projects with a focus on practical problem-solving and real-world applications."
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Mina Kebriaee"
github_username: "NeuralByteJourney"
linkedin_username: "mina-kebriae"
email: "mkebriae@uwaterloo.ca"
exclude:
  - "README.md"
